/// <reference path="references.ts"/>
var ITEMS: {[itemID:string]:Item};
ITEMS = {};

ITEMS[Items.BrokenSword] =                  {type: ItemType.Weapon,        name:'Broken Sword',                     weight:1000,  bulk:5000,   buy:NaN,          sell:25,     sprite:{type:ResourceType.Items, offset:{x:0, y:25}}, class:0  };
ITEMS[Items.Club] =                         {type: ItemType.Weapon,        name:'Club',                             weight:1500,  bulk:3000,   buy:105,          sell:60,     sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:1  };
ITEMS[Items.Dagger] =                       {type: ItemType.Weapon,        name:'Dagger',                           weight:500,   bulk:500,    buy:420,          sell:240,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:2  };
ITEMS[Items.Hammer] =                       {type: ItemType.Weapon,        name:'Hammer',                           weight:2000,  bulk:3000,   buy:420,          sell:240,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:2  };
ITEMS[Items.HandAxe] =                      {type: ItemType.Weapon,        name:'Hand Axe',                         weight:1000,  bulk:3000,   buy:472,          sell:270,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:3  };
ITEMS[Items.Quarterstaff] =                 {type: ItemType.Weapon,        name:'Quarterstaff',                     weight:750,   bulk:5000,   buy:648,          sell:360,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:3  };
ITEMS[Items.Spear] =                        {type: ItemType.Weapon,        name:'Spear',                            weight:1500,  bulk:5000,   buy:840,          sell:480,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:4  };
ITEMS[Items.ShortSword] =                   {type: ItemType.Weapon,        name:'Short Sword',                      weight:1000,  bulk:5000,   buy:1470,         sell:840,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:5  };
ITEMS[Items.Mace] =                         {type: ItemType.Weapon,        name:'Mace',                             weight:2500,  bulk:4375,   buy:1728,         sell:960,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:5  };
ITEMS[Items.Flail] =                        {type: ItemType.Weapon,        name:'Flail',                            weight:2000,  bulk:3250,   buy:1512,         sell:840,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:6  };
ITEMS[Items.Axe] =                          {type: ItemType.Weapon,        name:'Axe',                              weight:2000,  bulk:5000,   buy:1944,         sell:1080,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:6  };
ITEMS[Items.WarHammer] =                    {type: ItemType.Weapon,        name:'War Hammer',                       weight:1400,  bulk:7500,   buy:2160,         sell:1200,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:7  };
ITEMS[Items.LongSword] =                    {type: ItemType.Weapon,        name:'Long Sword',                       weight:1500,  bulk:8000,   buy:3240,         sell:1800,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:8  };
ITEMS[Items.BattleAxe] =                    {type: ItemType.Weapon,        name:'Battle Axe',                       weight:3000,  bulk:6000,   buy:2160,         sell:1200,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:8  };
ITEMS[Items.BroadSword] =                   {type: ItemType.Weapon,        name:'Broad Sword',                      weight:1600,  bulk:9000,   buy:3240,         sell:1800,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:9  };
ITEMS[Items.Morningstar] =                  {type: ItemType.Weapon,        name:'Morningstar',                      weight:3000,  bulk:9000,   buy:2160,         sell:1200,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:10 };
ITEMS[Items.BastardSword] =                 {type: ItemType.Weapon,        name:'Bastard Sword',                    weight:3000,  bulk:10000,  buy:4320,         sell:2400,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:11 };
ITEMS[Items.TwoHandedSword] =               {type: ItemType.Weapon,        name:'Two Handed Sword',                 weight:5000,  bulk:12000,  buy:6360,         sell:3600,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  class:12 };
ITEMS[Items.RustyArmor] =                   {type: ItemType.Armour,        name:'Rusty Armor',                      weight:10000, bulk:30000,  buy:NaN,          sell:25,     sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:0     };
ITEMS[Items.LeatherArmor] =                 {type: ItemType.Armour,        name:'Leather Armor',                    weight:5000,  bulk:2400,   buy:1080,         sell:600,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:6     };
ITEMS[Items.StuddedLeatherArmor] =          {type: ItemType.Armour,        name:'Studded Leather Armor',            weight:7000,  bulk:25000,  buy:3150,         sell:1800,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:12    };
ITEMS[Items.RingMail] =                     {type: ItemType.Armour,        name:'Ring Mail',                        weight:8000,  bulk:30000,  buy:6300,         sell:3600,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:18    };
ITEMS[Items.ScaleMail] =                    {type: ItemType.Armour,        name:'Scale Mail',                       weight:9000,  bulk:30000,  buy:10800,        sell:6000,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:24    };
ITEMS[Items.ChainMail] =                    {type: ItemType.Armour,        name:'Chain Mail',                       weight:10000, bulk:30000,  buy:16200,        sell:9000,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:30    };
ITEMS[Items.SplintMail] =                   {type: ItemType.Armour,        name:'Splint Mail',                      weight:12000, bulk:40000,  buy:27000,        sell:15000,  sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:36    };
ITEMS[Items.PlateMail] =                    {type: ItemType.Armour,        name:'Plate Mail',                       weight:15000, bulk:40000,  buy:42000,        sell:24000,  sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:42    };
ITEMS[Items.PlateArmor] =                   {type: ItemType.Armour,        name:'Plate Armor',                      weight:15000, bulk:60000,  buy:42000,        sell:24000,  sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:48    };
ITEMS[Items.MeteoricSteelPlate] =           {type: ItemType.Armour,        name:'Meteoric Steel Plate',             weight:5000,  bulk:30000,  buy:105000,       sell:60000,  sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:54    };
ITEMS[Items.ElvenChainMail] =               {type: ItemType.Armour,        name:'Elven Chain Mail',                 weight:50000, bulk:24000,  buy:162000,       sell:90000,  sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:52    };
ITEMS[Items.BrokenShield] =                 {type: ItemType.Shield,        name:'Broken Shield',                    weight:4000,  bulk:35000,  buy:NaN,          sell:25,     sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:0     };
ITEMS[Items.SmallWoodenShield] =            {type: ItemType.Shield,        name:'Small Wooden Shield',              weight:3000,  bulk:15000,  buy:525,          sell:300,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:3     };
ITEMS[Items.MediumWoodenShield] =           {type: ItemType.Shield,        name:'Medium Wooden Shield',             weight:4000,  bulk:35000,  buy:1050,         sell:600,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:6     };
ITEMS[Items.SmallIronShield] =              {type: ItemType.Shield,        name:'Small Iron Shield',                weight:4000,  bulk:15000,  buy:1260,         sell:720,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:6     };
ITEMS[Items.LargeWoodenShield] =            {type: ItemType.Shield,        name:'Large Wooden Shield',              weight:5000,  bulk:50000,  buy:2100,         sell:1200,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:9     };
ITEMS[Items.MediumIronShield] =             {type: ItemType.Shield,        name:'Medium Iron Shield',               weight:5000,  bulk:35000,  buy:2592,         sell:1440,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:9     };
ITEMS[Items.SmallSteelShield] =             {type: ItemType.Shield,        name:'Small Steel Shield',               weight:4000,  bulk:15000,  buy:2730,         sell:1560,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:9     };
ITEMS[Items.LargeIronShield] =              {type: ItemType.Shield,        name:'Large Iron Shield',                weight:6000,  bulk:50000,  buy:3150,         sell:1800,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:12    };
ITEMS[Items.MediumSteelShield] =            {type: ItemType.Shield,        name:'Medium Steel Shield',              weight:5000,  bulk:35000,  buy:3360,         sell:1920,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:12    };
ITEMS[Items.LargeSteelShield] =             {type: ItemType.Shield,        name:'Large Steel Shield',               weight:6000,  bulk:50000,  buy:4200,         sell:2400,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:15    };
ITEMS[Items.SmallMeteoricSteelShield] =     {type: ItemType.Shield,        name:'Small Meteoric Steel Shield',      weight:2500,  bulk:10000,  buy:4620,         sell:2640,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:15    };
ITEMS[Items.MediumMeteoricSteelShield] =    {type: ItemType.Shield,        name:'Medium Meteoric Steel Shield',     weight:3500,  bulk:25000,  buy:5940,         sell:3300,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:18    };
ITEMS[Items.LargeMeteoricSteelShield] =     {type: ItemType.Shield,        name:'Large Meteoric Steel Shield',      weight:4500,  bulk:35000,  buy:7560,         sell:4200,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:21    };
ITEMS[Items.BrokenHelmet] =                 {type: ItemType.Helmet,        name:'Broken Helmet',                    weight:1000,  bulk:1000,   buy:NaN,          sell:25,     sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:0     };
ITEMS[Items.LeatherHelmet] =                {type: ItemType.Helmet,        name:'Leather Helmet',                   weight:500,   bulk:500,    buy:525,          sell:300,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:3     };
ITEMS[Items.IronHelmet] =                   {type: ItemType.Helmet,        name:'Iron Helmet',                      weight:2000,  bulk:2000,   buy:1050,         sell:600,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:6     };
ITEMS[Items.SteelHelmet] =                  {type: ItemType.Helmet,        name:'Steel Helmet',                     weight:2500,  bulk:2000,   buy:3150,         sell:1800,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:9     };
ITEMS[Items.MeteoricSteelHelmet] =          {type: ItemType.Helmet,        name:'Meteoric Steel Helmet',            weight:1000,  bulk:2000,   buy:10500,        sell:6000,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:15    };
ITEMS[Items.HelmetofDetectMonsters] =       {type: ItemType.Helmet,        name:'Helmet of Detect Monsters',        weight:2500,  bulk:2000,   buy:42000,        sell:24000,  sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:9     };
ITEMS[Items.EnchantedHelmofStorms] =        {type: ItemType.Helmet,        name:'Enchanted Helm of Storms',         weight:1000,  bulk:2000,   buy:1050000,      sell:600000, sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:25    };
ITEMS[Items.Bracers] =                      {type: ItemType.Bracer,        name:'Bracers',                          weight:500,   bulk:2000,   buy:108,          sell:60,     sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:3     };
ITEMS[Items.BracersOfDefenseNormal] =       {type: ItemType.Bracer,        name:'Bracers Of Defense',               weight:500,   bulk:2000,   buy:1836,         sell:1020,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:8     };
ITEMS[Items.BracersOfDefenseS] =            {type: ItemType.Bracer,        name:'Bracers Of Defense',               weight:500,   bulk:2000,   buy:5616,         sell:3120,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:13    };
ITEMS[Items.BracersOfDefenseVS] =           {type: ItemType.Bracer,        name:'Bracers Of Defense',               weight:500,   bulk:2000,   buy:11556,        sell:6420,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:18    };
ITEMS[Items.Gauntlet] =                     {type: ItemType.Gauntlet,      name:'Gauntlets',                        weight:500,   bulk:2000,   buy:105,          sell:60,     sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:5     };
ITEMS[Items.GauntletOfProtection] =         {type: ItemType.Gauntlet,      name:'Gauntlets of Protection',          weight:500,   bulk:2000,   buy:2625,         sell:1500,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:NaN   };
ITEMS[Items.GauntletOfProtectionS] =        {type: ItemType.Gauntlet,      name:'Gauntlets of Protection',          weight:500,   bulk:2000,   buy:6300,         sell:3600,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:NaN   };
ITEMS[Items.GauntletOfProtectionVS] =       {type: ItemType.Gauntlet,      name:'Gauntlets of Protection',          weight:500,   bulk:2000,   buy:12420,        sell:6900,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:20    };
ITEMS[Items.GauntletOfSlaying] =            {type: ItemType.Gauntlet,      name:'Gauntlets of Slaying',             weight:500,   bulk:2000,   buy:3780,         sell:2100,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:0     };
ITEMS[Items.GauntletOfSlayingS_S] =         {type: ItemType.Gauntlet,      name:'Gauntlets of Slaying',             weight:500,   bulk:2000,   buy:7560,         sell:4200,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:0     };
ITEMS[Items.GauntletOfSlayingVS_VS] =       {type: ItemType.Gauntlet,      name:'Gauntlets of Slaying',             weight:500,   bulk:2000,   buy:13125,        sell:7500,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:0     };
ITEMS[Items.GauntletOfDexterity] =          {type: ItemType.Gauntlet,      name:'Gauntlets of Dexterity',           weight:500,   bulk:2000,   buy:3240,         sell:1800,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:5     };
ITEMS[Items.GauntletOfDexterityS] =         {type: ItemType.Gauntlet,      name:'Gauntlets of Dexterity',           weight:500,   bulk:2000,   buy:7020,         sell:3900,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:5     };
ITEMS[Items.GauntletOfDexterityVS] =        {type: ItemType.Gauntlet,      name:'Gauntlets of Dexterity',           weight:500,   bulk:2000,   buy:12960,        sell:7200,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:5     };
ITEMS[Items.GauntletOfStrength] =           {type: ItemType.Gauntlet,      name:'Gauntlets Of Strength',            weight:500,   bulk:2000,   buy:3240,         sell:1800,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:5     };
ITEMS[Items.GauntletOfStrengthS] =          {type: ItemType.Gauntlet,      name:'Gauntlets Of Strength',            weight:500,   bulk:2000,   buy:0,            sell:0,      sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:5     };
ITEMS[Items.GauntletOfStrengthVS] =         {type: ItemType.Gauntlet,      name:'Gauntlets Of Strength',            weight:500,   bulk:2000,   buy:12960,        sell:7200,   sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  ac:5     };
ITEMS[Items.TwoSlotbelt] =                  {type: ItemType.Belt,          name:'Two slot belt',                    weight:300,   bulk:300,    buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:2100,   bulkCap:3100, slot:2};
ITEMS[Items.ThreeSlotbelt] =                {type: ItemType.Belt,          name:'Three slot belt',                  weight:300,   bulk:300,    buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:2600,   bulkCap:3600, slot:3};
ITEMS[Items.FourSlotbelt] =                 {type: ItemType.Belt,          name:'Four slot belt',                   weight:300,   bulk:300,    buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:3100,   bulkCap:4100, slot:4};
ITEMS[Items.UtilityBelt] =                  {type: ItemType.Belt,          name:'Utility Belt',                     weight:1350,  bulk:1800,   buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:3100,   bulkCap:4100, slot:2, slotScroll:4, slotPotion:4};
ITEMS[Items.WandQuiverBelt] =               {type: ItemType.Belt,          name:'Wand Quiver Belt',                 weight:300,   bulk:300,    buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:3100,   bulkCap:4100, slot:2, slotWand:4};
ITEMS[Items.Purse] =                        {type: ItemType.Purse,         name:'Purse',                            weight:300,   bulk:300,    buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:100300, bulkCap:100300};
ITEMS[Items.SmallBag] =                     {type: ItemType.Bag,           name:'Small Bag',                        weight:300,   bulk:500,    buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:5000,   bulkCap:6000};
ITEMS[Items.MediumBag] =                    {type: ItemType.Bag,           name:'Medium Bag',                       weight:500,   bulk:700,    buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:10000,  bulkCap:12000};
ITEMS[Items.LargeBag] =                     {type: ItemType.Bag,           name:'Large Bag',                        weight:900,   bulk:900,    buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:15000,  bulkCap:18000};
ITEMS[Items.SmallPack] =                    {type: ItemType.Pack,          name:'Small Pack',                       weight:1000,  bulk:1000,   buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:12000,  bulkCap:50000};
ITEMS[Items.MediumPack] =                   {type: ItemType.Pack,          name:'Medium Pack',                      weight:2000,  bulk:1500,   buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:22000,  bulkCap:75000};
ITEMS[Items.LargePack] =                    {type: ItemType.Pack,          name:'Large Pack',                       weight:4000,  bulk:100000, buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:35000,  bulkCap:100000};
ITEMS[Items.SmallChest] =                   {type: ItemType.Chest,         name:'Small Chest',                      weight:5000,  bulk:100000, buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:100000, bulkCap:50000};
ITEMS[Items.MediumChest] =                  {type: ItemType.Chest,         name:'Medium Chest',                     weight:15000, bulk:150000, buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:100000, bulkCap:150000};
ITEMS[Items.LargeChest] =                   {type: ItemType.Chest,         name:'Large Chest',                      weight:25000, bulk:250000, buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:100000, bulkCap:250000};
ITEMS[Items.EnchantedSmallPackofHolding] =  {type: ItemType.PackOfHolding, name:'Enchanted Small Pack of Holding',  weight:5000,  bulk:75000,  buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:50000,  bulkCap:150000};
ITEMS[Items.EnchantedMediumPackofHolding] = {type: ItemType.PackOfHolding, name:'Enchanted Medium Pack of Holding', weight:7500,  bulk:100000, buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:75000,  bulkCap:200000};
ITEMS[Items.EnchantedLargePackofHolding] =  {type: ItemType.PackOfHolding, name:'Enchanted Large Pack of Holding',  weight:10000, bulk:125000, buy:NaN,          sell:NaN,    sprite:{type:ResourceType.Items, offset:{x:0, y:0}},  level:NaN, weightCap:100000, bulkCap:250000};

// chests have fixed bulk
// pack of holdings have fixed bulk and weight
//Trinklets

//{type:Potion, weight:200,   bulk:200}
//{type:Scroll,  weight:150,   bulk:200}
//{type:Amulet,  weight:200,   bulk:350}
//{type:Staff,   weight:750,   bulk:5000}
//{type:Boots,   weight:1500,  bulk:4000}
//{type:Cloak,   weight:500,   bulk:6000}
//{type:Ring,    weight:50,    bulk:30}
