/// <reference path="references.ts"/>
var CoTWSprites = {
    Actors: {
        Player: {type:ResourceType.Monsters, offset: {x: 0, y: 0},  size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Kobold: {type:ResourceType.Monsters, offset: {x: 64, y: 0}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0}
    },
    Tiles: {
        Rock:          {type:ResourceType.Tiles, offset: {x: 0  , y: 0  }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Grass:         {type:ResourceType.Tiles, offset: {x: 0  , y: 32 }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        DarkDgn:       {type:ResourceType.Tiles, offset: {x: 0  , y: 64 }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Water:         {type:ResourceType.Tiles, offset: {x: 0  , y: 96 }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Path:          {type:ResourceType.Tiles, offset: {x: 0  , y: 128}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        LitDgn:        {type:ResourceType.Tiles, offset: {x: 0  , y: 160}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        PathRock:      {type:ResourceType.Tiles, offset: {x: 32 , y: 0  }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        PathGrass:     {type:ResourceType.Tiles, offset: {x: 32 , y: 32 }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        WallDarkDgn:   {type:ResourceType.Tiles, offset: {x: 32 , y: 64 }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        WaterGrass:    {type:ResourceType.Tiles, offset: {x: 32 , y: 96 }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        WaterPath:     {type:ResourceType.Tiles, offset: {x: 32 , y: 128}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        WallLitDgn:    {type:ResourceType.Tiles, offset: {x: 32 , y: 160}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Grass50Cave50: {type:ResourceType.Tiles, offset: {x: 0  , y: 192}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Grass10Cave90: {type:ResourceType.Tiles, offset: {x: 32 , y: 192}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        White50Cave50: {type:ResourceType.Tiles, offset: {x: 0  , y: 224}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        White90Cave10: {type:ResourceType.Tiles, offset: {x: 32 , y: 224}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Crop:          {type:ResourceType.Tiles, offset: {x: 64 , y: 32 }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Entry:         {type:ResourceType.Tiles, offset: {x: 192, y: 160}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Building:      {type:ResourceType.Tiles, offset: {x: 192, y: 160}, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0},
        Sign:          {type:ResourceType.Tiles, offset: {x: 160, y: 0  }, size: {w: TILE_SIZE, h: TILE_SIZE}, turn:0}
    },
    Buildings: {
        Gate_NS             : {type:ResourceType.buildings_1x, offset: {x:0,  y:0}, size:{w:96, h:32},  turn:0},
        StrawHouse_EF       : {type:ResourceType.buildings_3x, offset: {x:0,  y:0}, size:{w:96, h:96},  turn:0},
        StrawHouse_WF       : {type:ResourceType.buildings_3x, offset: {x:192,y:0}, size:{w:96, h:96},  turn:0},
        Hut_EF              : {type:ResourceType.buildings_2x, offset: {x:0,  y:0}, size:{w:64, h:64},  turn:0},
        HutTemple_NF        : {type:ResourceType.buildings_5x, offset: {x:0,  y:0}, size:{w:160,h:160}, turn:0},
        BurntStrawHouse_WF  : {type:ResourceType.buildings_3x, offset: {x:288,y:0}, size:{w:96, h:96},  turn:0}
    },
    Items: {
        BrokenSword                   : {type:ResourceType.Items, offset:{x:0, y:25}},
        Club                          : {type:ResourceType.Items, offset:{x:0, y:0}},
        Dagger                        : {type:ResourceType.Items, offset:{x:0, y:0}},
        Hammer                        : {type:ResourceType.Items, offset:{x:0, y:0}},
        HandAxe                       : {type:ResourceType.Items, offset:{x:0, y:0}},
        Quarterstaff                  : {type:ResourceType.Items, offset:{x:0, y:0}},
        Spear                         : {type:ResourceType.Items, offset:{x:0, y:0}},
        ShortSword                    : {type:ResourceType.Items, offset:{x:0, y:0}},
        Mace                          : {type:ResourceType.Items, offset:{x:0, y:0}},
        Flail                         : {type:ResourceType.Items, offset:{x:0, y:0}},
        Axe                           : {type:ResourceType.Items, offset:{x:0, y:0}},
        WarHammer                     : {type:ResourceType.Items, offset:{x:0, y:0}},
        LongSword                     : {type:ResourceType.Items, offset:{x:0, y:0}},
        BattleAxe                     : {type:ResourceType.Items, offset:{x:0, y:0}},
        BroadSword                    : {type:ResourceType.Items, offset:{x:0, y:0}},
        Morningstar                   : {type:ResourceType.Items, offset:{x:0, y:0}},
        BastardSword                  : {type:ResourceType.Items, offset:{x:0, y:0}},
        TwoHandedSword                : {type:ResourceType.Items, offset:{x:0, y:0}},
        RustyArmor                    : {type:ResourceType.Items, offset:{x:0, y:0}},
        LeatherArmor                  : {type:ResourceType.Items, offset:{x:0, y:0}},
        StuddedLeatherArmor           : {type:ResourceType.Items, offset:{x:0, y:0}},
        RingMail                      : {type:ResourceType.Items, offset:{x:0, y:0}},
        ScaleMail                     : {type:ResourceType.Items, offset:{x:0, y:0}},
        ChainMail                     : {type:ResourceType.Items, offset:{x:0, y:0}},
        SplintMail                    : {type:ResourceType.Items, offset:{x:0, y:0}},
        PlateMail                     : {type:ResourceType.Items, offset:{x:0, y:0}},
        PlateArmor                    : {type:ResourceType.Items, offset:{x:0, y:0}},
        MeteoricSteelPlate            : {type:ResourceType.Items, offset:{x:0, y:0}},
        ElvenChainMail                : {type:ResourceType.Items, offset:{x:0, y:0}},
        BrokenShield                  : {type:ResourceType.Items, offset:{x:0, y:0}},
        SmallWoodenShield             : {type:ResourceType.Items, offset:{x:0, y:0}},
        MediumWoodenShield            : {type:ResourceType.Items, offset:{x:0, y:0}},
        SmallIronShield               : {type:ResourceType.Items, offset:{x:0, y:0}},
        LargeWoodenShield             : {type:ResourceType.Items, offset:{x:0, y:0}},
        MediumIronShield              : {type:ResourceType.Items, offset:{x:0, y:0}},
        SmallSteelShield              : {type:ResourceType.Items, offset:{x:0, y:0}},
        LargeIronShield               : {type:ResourceType.Items, offset:{x:0, y:0}},
        MediumSteelShield             : {type:ResourceType.Items, offset:{x:0, y:0}},
        LargeSteelShield              : {type:ResourceType.Items, offset:{x:0, y:0}},
        SmallMeteoricSteelShield      : {type:ResourceType.Items, offset:{x:0, y:0}},
        MediumMeteoricSteelShield     : {type:ResourceType.Items, offset:{x:0, y:0}},
        LargeMeteoricSteelShield      : {type:ResourceType.Items, offset:{x:0, y:0}},
        BrokenHelmet                  : {type:ResourceType.Items, offset:{x:0, y:0}},
        LeatherHelmet                 : {type:ResourceType.Items, offset:{x:0, y:0}},
        IronHelmet                    : {type:ResourceType.Items, offset:{x:0, y:0}},
        SteelHelmet                   : {type:ResourceType.Items, offset:{x:0, y:0}},
        MeteoricSteelHelmet           : {type:ResourceType.Items, offset:{x:0, y:0}},
        HelmetofDetectMonsters        : {type:ResourceType.Items, offset:{x:0, y:0}},
        EnchantedHelmofStorms         : {type:ResourceType.Items, offset:{x:0, y:0}},
        Bracers                       : {type:ResourceType.Items, offset:{x:0, y:0}},
        BracersOfDefenseNormal        : {type:ResourceType.Items, offset:{x:0, y:0}},
        BracersOfDefenseS             : {type:ResourceType.Items, offset:{x:0, y:0}},
        BracersOfDefenseVS            : {type:ResourceType.Items, offset:{x:0, y:0}},
        Gauntlet                      : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfProtection          : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfProtectionS         : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfProtectionVS        : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfSlaying             : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfSlayingS_S          : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfSlayingVS_VS        : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfDexterity           : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfDexterityS          : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfDexterityVS         : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfStrength            : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfStrengthS           : {type:ResourceType.Items, offset:{x:0, y:0}},
        GauntletOfStrengthVS          : {type:ResourceType.Items, offset:{x:0, y:0}},
        TwoSlotbelt                   : {type:ResourceType.Items, offset:{x:0, y:0}},
        ThreeSlotbelt                 : {type:ResourceType.Items, offset:{x:0, y:0}},
        FourSlotbelt                  : {type:ResourceType.Items, offset:{x:0, y:0}},
        UtilityBelt                   : {type:ResourceType.Items, offset:{x:0, y:0}},
        WandQuiverBelt                : {type:ResourceType.Items, offset:{x:0, y:0}},
        Purse                         : {type:ResourceType.Items, offset:{x:0, y:0}},
        SmallBag                      : {type:ResourceType.Items, offset:{x:0, y:0}},
        MediumBag                     : {type:ResourceType.Items, offset:{x:0, y:0}},
        LargeBag                      : {type:ResourceType.Items, offset:{x:0, y:0}},
        SmallPack                     : {type:ResourceType.Items, offset:{x:0, y:0}},
        MediumPack                    : {type:ResourceType.Items, offset:{x:0, y:0}},
        LargePack                     : {type:ResourceType.Items, offset:{x:0, y:0}},
        SmallChest                    : {type:ResourceType.Items, offset:{x:0, y:0}},
        MediumChest                   : {type:ResourceType.Items, offset:{x:0, y:0}},
        LargeChest                    : {type:ResourceType.Items, offset:{x:0, y:0}},
        EnchantedSmallPackofHolding   : {type:ResourceType.Items, offset:{x:0, y:0}},
        EnchantedMediumPackofHolding  : {type:ResourceType.Items, offset:{x:0, y:0}},
        EnchantedLargePackofHolding   : {type:ResourceType.Items, offset:{x:0, y:0}}
    }
};