/// <reference path="references.ts"/>
/**
* Too many items use the same images, these refer to those images, used by CoTWContent
*/
var ItemOffsets = {
    Club: { x: 0, y: 896 },
    Hammer: { x: 0, y: 768 },
    Spear: { x: 0, y: 864 },
    Sword: { x: 0, y: 192 },
    Mace: { x: 0, y: 224 },
    Flail: { x: 0, y: 736 },
    Axe: { x: 0, y: 160 },
    MorningStar: { x: 0, y: 832 },
    LeatherArmour: { x: 0, y: 256 },
    MetalArmour: { x: 0, y: 288 },
    WoodShield: { x: 0, y: 352 },
    MetalShield: { x: 0, y: 320 },
    LeatherHelmet: { x: 0, y: 416 },
    MetalHelmet: { x: 0, y: 384 },
    HelmetOfDetectMonsters: { x: 98, y: 384 },
    Bracers: { x: 0, y: 448 },
    BracersEnchanted: { x: 32, y: 448 },
    Gauntlet: { x: 0, y: 480 },
    GauntletEnchanted: { x: 32, y: 480 },
    GauntletOfSlaying: { x: 92, y: 480 },
    SlotBelt: { x: 0, y: 672 },
    WandQuiverBelt: { x: 32, y: 672 },
    UtilityBelt: { x: 64, y: 672 },
    Boots: { x: 0, y: 544 },
    BootsOfSpeed: { x: 64, y: 544 },
    BootsOfLevitation: { x: 96, y: 544 },
    Cloak: { x: 0, y: 512 },
    Ring: { x: 0, y: 576 },
    Amulet: { x: 0, y: 128 },
    AmuletCursed: { x: 32, y: 128 },
    AmuletResistFire: { x: 64, y: 128 },
    AmuletResistLightning: { x: 96, y: 128 },
    AmuletResistCold: { x: 128, y: 128 },
    AmuletResistDrain: { x: 160, y: 128 },
    Wand: { x: 0, y: 96 },
    WandOfFireBall: { x: 32, y: 96 },
    WandOfLightningBall: { x: 64, y: 96 },
    WandOfLight: { x: 96, y: 96 },
    WandOfDivination: { x: 128, y: 96 },
    WandOfNothing: { x: 160, y: 96 },
    WandOfColdBall: { x: 192, y: 96 },
    WandOfColdBolt: { x: 224, y: 96 },
    WandOfFireBolt: { x: 256, y: 96 },
    WandOfLightning: { x: 288, y: 96 },
    Staff: { x: 0, y: 64 },
    StaffFire: { x: 32, y: 64 },
    StaffSmoke: { x: 64, y: 64 },
    StaffMinor: { x: 96, y: 64 },
    StaffMedium: { x: 128, y: 64 },
    StaffMajor: { x: 160, y: 64 },
    StaffGreen: { x: 192, y: 64 },
    StaffLight: { x: 224, y: 64 },
    Scroll: { x: 256, y: 32 },
    SpellBook: { x: 32, y: 32 },
    Potion: { x: 0, y: 0 },
    PotionWater: { x: 32, y: 0 },
    PotionMinorHeal: { x: 64, y: 0 },
    PotionMediumHeal: { x: 96, y: 0 },
    PotionMajorHeal: { x: 128, y: 0 },
    PotionGainAttribute: { x: 160, y: 0 },
    PotionLoseAttribute: { x: 192, y: 0 },
    PotionDivination: { x: 224, y: 0 },
    Purse: { x: 0, y: 608 },
    Bag: { x: 32, y: 608 },
    Pack: { x: 96, y: 608 },
    Chest: { x: 64, y: 608 },
    EnchantedPack: { x: 128, y: 608 },
    CoinsCopper: { x: 0, y: 640 },
    CoinsSilver: { x: 32, y: 640 },
    CoinsGold: { x: 64, y: 640 },
    CoinsPlatinum: { x: 96, y: 640 },
    TreasurePile: { x: 128, y: 640 },
    Parchment: { x: 0, y: 704 },
    EnchantedHelmOfStorms: { x: 32, y: 704 },
    ElementalPortal: { x: 64, y: 704 },
    AmuletOfKings: { x: 96, y: 704 },
    Apple: { x: 128, y: 704 },
    BrokenSword: { x: 0, y: 800 },
    BrokenArmour: { x: 32, y: 800 },
    BrokenShield: { x: 64, y: 800 },
    BrokenHelmet: { x: 96, y: 800 },
    BrokenBelt: { x: 128, y: 800 },
    BrokenGauntlet: { x: 160, y: 800 },
    BrokenBracer: { x: 192, y: 800 },
    BrokenCloak: { x: 224, y: 800 },
    BrokenPack: { x: 256, y: 800 },
    BrokenBoot: { x: 288, y: 800 }
};

/**
* Maps all cotw objects that are graphical to the file and location/size of the image
*/
var CoTWContent = {
    Buildings: {
        Gate_NS: { entryPoint: { x: 1, y: 0 }, sprite: { offset: { x: 0, y: 0 }, size: { w: 96, h: 32 } } },
        Hut_EF: { entryPoint: { x: 1, y: 0 }, sprite: { offset: { x: 0, y: 0 }, size: { w: 64, h: 64 } } },
        StrawHouse_EF: { entryPoint: { x: 2, y: 1 }, sprite: { offset: { x: 0, y: 0 }, size: { w: 96, h: 96 } } },
        StrawHouse_WF: { entryPoint: { x: 0, y: 1 }, sprite: { offset: { x: 192, y: 0 }, size: { w: 96, h: 96 } } },
        BurntStrawHouse_WF: { entryPoint: { x: 0, y: 1 }, sprite: { offset: { x: 288, y: 0 }, size: { w: 96, h: 96 } } },
        HutTemple_NF: { entryPoint: { x: 2, y: 1 }, sprite: { offset: { x: 0, y: 0 }, size: { w: 160, h: 160 } } },
        MineEntrance: { sprite: { file: ResourceFile.Tiles, offset: { x: 64, y: 0 } } },
        Fountain: { sprite: { file: ResourceFile.Tiles, offset: { x: 96, y: 96 } } },
        Sign: { sprite: { file: ResourceFile.Tiles, offset: { x: 160, y: 0 } } },
        Well: { sprite: { file: ResourceFile.Tiles, offset: { x: 160, y: 32 } } },
        VegePatch: { sprite: { file: ResourceFile.Tiles, offset: { x: 128, y: 32 } } },
        Wagon: { sprite: { file: ResourceFile.Tiles, offset: { x: 192, y: 32 } } },
        StairsDown: { sprite: { file: ResourceFile.Tiles, offset: { x: 96, y: 128 } } },
        StairsUp: { sprite: { file: ResourceFile.Tiles, offset: { x: 64, y: 128 } } },
        DoorClosed: { sprite: { file: ResourceFile.Tiles, offset: { x: 64, y: 160 } } },
        DoorOpen: { sprite: { file: ResourceFile.Tiles, offset: { x: 96, y: 160 } } }
    },
    Actors: {
        MaleHero: { sprite: { offset: { x: 0, y: 0 } } },
        FemaleHero: { sprite: { offset: { x: 32, y: 0 } } },
        Kobold: { sprite: { offset: { x: 64, y: 0 } } },
        GiantRat: { sprite: { offset: { x: 96, y: 0 } } },
        LargeSnake: { sprite: { offset: { x: 128, y: 0 } } },
        GiantAnt: { sprite: { offset: { x: 160, y: 0 } } },
        WildDog: { sprite: { offset: { x: 192, y: 0 } } },
        Skeleton: { sprite: { offset: { x: 224, y: 0 } } },
        GiantTrapdoorSpider: { sprite: { offset: { x: 256, y: 0 } } },
        GiantBat: { sprite: { offset: { x: 288, y: 0 } } },
        CarrionCreeper: { sprite: { offset: { x: 320, y: 0 } } },
        GiantScorpion: { sprite: { offset: { x: 352, y: 0 } } },
        GreenSlime: { sprite: { offset: { x: 384, y: 0 } } },
        Viper: { sprite: { offset: { x: 416, y: 0 } } },
        Ogre: { sprite: { offset: { x: 0, y: 32 } } },
        WalkingCorpse: { sprite: { offset: { x: 32, y: 32 } } },
        HugeLizard: { sprite: { offset: { x: 64, y: 32 } } },
        Goblin: { sprite: { offset: { x: 96, y: 32 } } },
        Hobgoblin: { sprite: { offset: { x: 128, y: 32 } } },
        Spectre: { sprite: { offset: { x: 160, y: 32 } } },
        Thief: { sprite: { offset: { x: 192, y: 32 } } },
        Wolf: { sprite: { offset: { x: 224, y: 32 } } },
        DireWolf: { sprite: { offset: { x: 256, y: 32 } } },
        BrownBear: { sprite: { offset: { x: 288, y: 32 } } },
        CaveBear: { sprite: { offset: { x: 320, y: 32 } } },
        GelatinousGlob: { sprite: { offset: { x: 352, y: 32 } } },
        Troll: { sprite: { offset: { x: 384, y: 32 } } },
        Manticore: { sprite: { offset: { x: 416, y: 32 } } },
        BronzeGolem: { sprite: { offset: { x: 0, y: 64 } } },
        IronGolem: { sprite: { offset: { x: 32, y: 64 } } },
        DiamondGolem: { sprite: { offset: { x: 64, y: 64 } } },
        WoodenGolem: { sprite: { offset: { x: 96, y: 64 } } },
        Bandit: { sprite: { offset: { x: 128, y: 64 } } },
        Warrior: { sprite: { offset: { x: 160, y: 64 } } },
        Wizard: { sprite: { offset: { x: 192, y: 64 } } },
        Necromancer: { sprite: { offset: { x: 224, y: 64 } } },
        Wight: { sprite: { offset: { x: 256, y: 64 } } },
        Wraith: { sprite: { offset: { x: 288, y: 64 } } },
        Ghost: { sprite: { offset: { x: 320, y: 64 } } },
        Shadow: { sprite: { offset: { x: 352, y: 64 } } },
        Vampire: { sprite: { offset: { x: 384, y: 64 } } },
        IceDevil: { sprite: { offset: { x: 416, y: 64 } } },
        RatMan: { sprite: { offset: { x: 0, y: 96 } } },
        WolfMan: { sprite: { offset: { x: 32, y: 96 } } },
        BearMan: { sprite: { offset: { x: 64, y: 96 } } },
        BullMan: { sprite: { offset: { x: 96, y: 96 } } },
        SpikedDevil: { sprite: { offset: { x: 128, y: 96 } } },
        HornedDevil: { sprite: { offset: { x: 160, y: 96 } } },
        AbyssFiend: { sprite: { offset: { x: 192, y: 96 } } },
        WindElemental: { sprite: { offset: { x: 224, y: 96 } } },
        DustElemental: { sprite: { offset: { x: 256, y: 96 } } },
        FireElemental: { sprite: { offset: { x: 288, y: 96 } } },
        WaterElemental: { sprite: { offset: { x: 320, y: 96 } } },
        MagmaElemental: { sprite: { offset: { x: 352, y: 96 } } },
        IceElemental: { sprite: { offset: { x: 384, y: 96 } } },
        EarthElemental: { sprite: { offset: { x: 416, y: 96 } } },
        HillGiant: { sprite: { offset: { x: 0, y: 128 } } },
        TwoHeadGiant: { sprite: { offset: { x: 32, y: 128 } } },
        FrostGiant: { sprite: { offset: { x: 64, y: 128 } } },
        StoneGiant: { sprite: { offset: { x: 96, y: 128 } } },
        FireGiant: { sprite: { offset: { x: 128, y: 128 } } },
        Surtur: { sprite: { offset: { x: 160, y: 128 } } },
        FireGiantKing: { sprite: { offset: { x: 192, y: 128 } } },
        FrostGiantKing: { sprite: { offset: { x: 224, y: 128 } } },
        HillGiantKing: { sprite: { offset: { x: 256, y: 128 } } },
        StoneGiantKing: { sprite: { offset: { x: 288, y: 128 } } },
        RedDragon: { sprite: { offset: { x: 320, y: 128 } } },
        BlueDragon: { sprite: { offset: { x: 352, y: 128 } } },
        WhiteDragon: { sprite: { offset: { x: 384, y: 128 } } },
        GreenDragon: { sprite: { offset: { x: 416, y: 128 } } }
    },
    Tiles: {
        Rock: { solid: true, name: 'Rock', sprite: { offset: { x: 0, y: 0 } } },
        Grass: { solid: false, name: 'Grass', sprite: { offset: { x: 0, y: 32 } } },
        DarkDgn: { solid: false, name: 'DarkDgn', sprite: { offset: { x: 0, y: 64 } } },
        Water: { solid: false, name: 'Water', sprite: { offset: { x: 0, y: 96 } } },
        Path: { solid: false, name: 'Path', sprite: { offset: { x: 0, y: 128 } } },
        LitDgn: { solid: false, name: 'LitDgn', sprite: { offset: { x: 0, y: 160 } } },
        PathRock: { solid: true, name: 'PathRock', sprite: { offset: { x: 32, y: 0 } } },
        PathGrass: { solid: false, name: 'PathGrass', sprite: { offset: { x: 32, y: 32 } } },
        WallDarkDgn: { solid: true, name: 'WallDarkDgn', sprite: { offset: { x: 32, y: 64 } } },
        WaterGrass: { solid: false, name: 'WaterGrass', sprite: { offset: { x: 32, y: 96 } } },
        WaterPath: { solid: false, name: 'WaterPath', sprite: { offset: { x: 32, y: 128 } } },
        WallLitDgn: { solid: true, name: 'WallLitDgn', sprite: { offset: { x: 32, y: 160 } } },
        Grass50Cave50: { solid: true, name: 'Grass50Cave50', sprite: { offset: { x: 0, y: 192 } } },
        Grass10Cave90: { solid: true, name: 'Grass10Cave90', sprite: { offset: { x: 32, y: 192 } } },
        White50Cave50: { solid: true, name: 'White50Cave50', sprite: { offset: { x: 0, y: 224 } } },
        White90Cave10: { solid: true, name: 'White90Cave10', sprite: { offset: { x: 32, y: 224 } } },
        Crop: { solid: true, name: 'Crop', sprite: { offset: { x: 64, y: 32 } } },
        Entry: { solid: false, name: 'Entry', sprite: { offset: { x: 0, y: 32 } } },
        Building: { solid: true, name: 'Building', sprite: { offset: { x: 0, y: 32 } } },
        TreasurePile: { solid: false, name: 'TreasurePile', sprite: { offset: { x: 128, y: 640 } } }
    },
    Items: {
        Weapon: {
            BrokenSword: { name: 'Broken Sword', weight: 1000, bulk: 5000, buy: NaN, sell: 25, weaponClass: 0, sprite: { offset: ItemOffsets.BrokenSword } },
            Club: { name: 'Club', weight: 1500, bulk: 3000, buy: 105, sell: 60, weaponClass: 1, sprite: { offset: ItemOffsets.Club } },
            Dagger: { name: 'Dagger', weight: 500, bulk: 500, buy: 420, sell: 240, weaponClass: 2, sprite: { offset: ItemOffsets.Sword } },
            Hammer: { name: 'Hammer', weight: 2000, bulk: 3000, buy: 420, sell: 240, weaponClass: 2, sprite: { offset: ItemOffsets.Hammer } },
            HandAxe: { name: 'Hand Axe', weight: 1000, bulk: 3000, buy: 472, sell: 270, weaponClass: 3, sprite: { offset: ItemOffsets.Axe } },
            Quarterstaff: { name: 'Quarterstaff', weight: 750, bulk: 5000, buy: 648, sell: 360, weaponClass: 3, sprite: { offset: ItemOffsets.Spear } },
            Spear: { name: 'Spear', weight: 1500, bulk: 5000, buy: 840, sell: 480, weaponClass: 4, sprite: { offset: ItemOffsets.Spear } },
            ShortSword: { name: 'Short Sword', weight: 1000, bulk: 5000, buy: 1470, sell: 840, weaponClass: 5, sprite: { offset: ItemOffsets.Sword } },
            Mace: { name: 'Mace', weight: 2500, bulk: 4375, buy: 1728, sell: 960, weaponClass: 5, sprite: { offset: ItemOffsets.Mace } },
            Flail: { name: 'Flail', weight: 2000, bulk: 3250, buy: 1512, sell: 840, weaponClass: 6, sprite: { offset: ItemOffsets.Flail } },
            Axe: { name: 'Axe', weight: 2000, bulk: 5000, buy: 1944, sell: 1080, weaponClass: 6, sprite: { offset: ItemOffsets.Axe } },
            WarHammer: { name: 'War Hammer', weight: 1400, bulk: 7500, buy: 2160, sell: 1200, weaponClass: 7, sprite: { offset: ItemOffsets.Hammer } },
            LongSword: { name: 'Long Sword', weight: 1500, bulk: 8000, buy: 3240, sell: 1800, weaponClass: 8, sprite: { offset: ItemOffsets.Sword } },
            BattleAxe: { name: 'Battle Axe', weight: 3000, bulk: 6000, buy: 2160, sell: 1200, weaponClass: 8, sprite: { offset: ItemOffsets.Axe } },
            BroadSword: { name: 'Broad Sword', weight: 1600, bulk: 9000, buy: 3240, sell: 1800, weaponClass: 9, sprite: { offset: ItemOffsets.Sword } },
            MorningStar: { name: 'Morning Star', weight: 3000, bulk: 9000, buy: 2160, sell: 1200, weaponClass: 10, sprite: { offset: ItemOffsets.MorningStar } },
            BastardSword: { name: 'Bastard Sword', weight: 3000, bulk: 10000, buy: 4320, sell: 2400, weaponClass: 11, sprite: { offset: ItemOffsets.Sword } },
            TwoHandedSword: { name: 'Two Handed Sword', weight: 5000, bulk: 12000, buy: 6360, sell: 3600, weaponClass: 12, sprite: { offset: ItemOffsets.Sword } }
        },
        Armour: {
            RustyArmour: { name: 'Rusty Armour', weight: 10000, bulk: 30000, buy: NaN, sell: 25, ac: 0, sprite: { offset: ItemOffsets.BrokenArmour } },
            LeatherArmour: { name: 'Leather Armour', weight: 5000, bulk: 2400, buy: 1080, sell: 600, ac: 6, sprite: { offset: ItemOffsets.LeatherArmour } },
            StuddedLeatherArmour: { name: 'Studded Leather Armour', weight: 7000, bulk: 25000, buy: 3150, sell: 1800, ac: 12, sprite: { offset: ItemOffsets.LeatherArmour } },
            RingMail: { name: 'Ring Mail', weight: 8000, bulk: 30000, buy: 6300, sell: 3600, ac: 18, sprite: { offset: ItemOffsets.MetalArmour } },
            ScaleMail: { name: 'Scale Mail', weight: 9000, bulk: 30000, buy: 10800, sell: 6000, ac: 24, sprite: { offset: ItemOffsets.MetalArmour } },
            ChainMail: { name: 'Chain Mail', weight: 10000, bulk: 30000, buy: 16200, sell: 9000, ac: 30, sprite: { offset: ItemOffsets.MetalArmour } },
            SplintMail: { name: 'Splint Mail', weight: 12000, bulk: 40000, buy: 27000, sell: 15000, ac: 36, sprite: { offset: ItemOffsets.MetalArmour } },
            PlateMail: { name: 'Plate Mail', weight: 15000, bulk: 40000, buy: 42000, sell: 24000, ac: 42, sprite: { offset: ItemOffsets.MetalArmour } },
            PlateArmour: { name: 'Plate Armour', weight: 15000, bulk: 60000, buy: 42000, sell: 24000, ac: 48, sprite: { offset: ItemOffsets.MetalArmour } },
            MeteoricSteelPlate: { name: 'Meteoric Steel Plate', weight: 5000, bulk: 30000, buy: 105000, sell: 60000, ac: 54, sprite: { offset: ItemOffsets.MetalArmour } },
            ElvenChainMail: { name: 'Elven Chain Mail', weight: 50000, bulk: 24000, buy: 162000, sell: 90000, ac: 52, sprite: { offset: ItemOffsets.MetalArmour } }
        },
        Shield: {
            BrokenShield: { name: 'Broken Shield', weight: 4000, bulk: 35000, buy: NaN, sell: 25, ac: 0, sprite: { offset: ItemOffsets.BrokenShield } },
            SmallWoodenShield: { name: 'Small Wooden Shield', weight: 3000, bulk: 15000, buy: 525, sell: 300, ac: 3, sprite: { offset: ItemOffsets.WoodShield } },
            MediumWoodenShield: { name: 'Medium Wooden Shield', weight: 4000, bulk: 35000, buy: 1050, sell: 600, ac: 6, sprite: { offset: ItemOffsets.WoodShield } },
            LargeWoodenShield: { name: 'Large Wooden Shield', weight: 5000, bulk: 50000, buy: 2100, sell: 1200, ac: 9, sprite: { offset: ItemOffsets.WoodShield } },
            SmallIronShield: { name: 'Small Iron Shield', weight: 4000, bulk: 15000, buy: 1260, sell: 720, ac: 6, sprite: { offset: ItemOffsets.MetalShield } },
            MediumIronShield: { name: 'Medium Iron Shield', weight: 5000, bulk: 35000, buy: 2592, sell: 1440, ac: 9, sprite: { offset: ItemOffsets.MetalShield } },
            LargeIronShield: { name: 'Large Iron Shield', weight: 6000, bulk: 50000, buy: 3150, sell: 1800, ac: 12, sprite: { offset: ItemOffsets.MetalShield } },
            SmallSteelShield: { name: 'Small Steel Shield', weight: 4000, bulk: 15000, buy: 2730, sell: 1560, ac: 9, sprite: { offset: ItemOffsets.MetalShield } },
            MediumSteelShield: { name: 'Medium Steel Shield', weight: 5000, bulk: 35000, buy: 3360, sell: 1920, ac: 12, sprite: { offset: ItemOffsets.MetalShield } },
            LargeSteelShield: { name: 'Large Steel Shield', weight: 6000, bulk: 50000, buy: 4200, sell: 2400, ac: 15, sprite: { offset: ItemOffsets.MetalShield } },
            SmallMeteoricSteelShield: { name: 'Small Meteoric Steel Shield', weight: 2500, bulk: 10000, buy: 4620, sell: 2640, ac: 15, sprite: { offset: ItemOffsets.MetalShield } },
            MediumMeteoricSteelShield: { name: 'Medium Meteoric Steel Shield', weight: 3500, bulk: 25000, buy: 5940, sell: 3300, ac: 18, sprite: { offset: ItemOffsets.MetalShield } },
            LargeMeteoricSteelShield: { name: 'Large Meteoric Steel Shield', weight: 4500, bulk: 35000, buy: 7560, sell: 4200, ac: 21, sprite: { offset: ItemOffsets.MetalShield } }
        },
        Helmet: {
            BrokenHelmet: { name: 'Broken Helmet', weight: 1000, bulk: 1000, buy: NaN, sell: 25, ac: 0, sprite: { offset: ItemOffsets.BrokenHelmet } },
            LeatherHelmet: { name: 'Leather Helmet', weight: 500, bulk: 500, buy: 525, sell: 300, ac: 3, sprite: { offset: ItemOffsets.LeatherHelmet } },
            IronHelmet: { name: 'Iron Helmet', weight: 2000, bulk: 2000, buy: 1050, sell: 600, ac: 6, sprite: { offset: ItemOffsets.MetalHelmet } },
            SteelHelmet: { name: 'Steel Helmet', weight: 2500, bulk: 2000, buy: 3150, sell: 1800, ac: 9, sprite: { offset: ItemOffsets.MetalHelmet } },
            MeteoricSteelHelmet: { name: 'Meteoric Steel Helmet', weight: 1000, bulk: 2000, buy: 10500, sell: 6000, ac: 15, sprite: { offset: ItemOffsets.MetalHelmet } },
            HelmetOfDetectMonsters: { name: 'Helmet Of Detect Monsters', weight: 2500, bulk: 2000, buy: 42000, sell: 24000, ac: 9, sprite: { offset: ItemOffsets.HelmetOfDetectMonsters } },
            EnchantedHelmOfStorms: { name: 'Enchanted Helm Of Storms', weight: 1000, bulk: 2000, buy: 1050000, sell: 600000, ac: 25, sprite: { offset: ItemOffsets.EnchantedHelmOfStorms } }
        },
        Bracer: {
            Bracers: { name: 'Bracers', weight: 500, bulk: 2000, buy: 108, sell: 60, ac: 3, sprite: { offset: ItemOffsets.Bracers } },
            BracersOfDefenseNormal: { name: 'Bracers Of Defense Normal', weight: 500, bulk: 2000, buy: 1836, sell: 1020, ac: 8, sprite: { offset: ItemOffsets.BracersEnchanted } },
            BracersOfDefenseS: { name: 'Bracers Of Defense Strong', weight: 500, bulk: 2000, buy: 5616, sell: 3120, ac: 13, sprite: { offset: ItemOffsets.BracersEnchanted } },
            BracersOfDefenseVS: { name: 'Bracers Of Defense Very Strong', weight: 500, bulk: 2000, buy: 11556, sell: 6420, ac: 18, sprite: { offset: ItemOffsets.BracersEnchanted } }
        },
        Gauntlet: {
            Gauntlet: { name: 'Gauntlet', weight: 500, bulk: 2000, buy: 105, sell: 60, ac: 5, sprite: { offset: ItemOffsets.Gauntlet } },
            GauntletOfProtection: { name: 'Gauntlet Of Protection', weight: 500, bulk: 2000, buy: 2625, sell: 1500, ac: 10, sprite: { offset: ItemOffsets.GauntletEnchanted } },
            GauntletOfProtectionS: { name: 'Gauntlet Of Protection Strong', weight: 500, bulk: 2000, buy: 6300, sell: 3600, ac: 15, sprite: { offset: ItemOffsets.GauntletEnchanted } },
            GauntletOfProtectionVS: { name: 'Gauntlet Of Protection Very Strong', weight: 500, bulk: 2000, buy: 12420, sell: 6900, ac: 20, sprite: { offset: ItemOffsets.GauntletEnchanted } },
            GauntletOfSlaying: { name: 'Gauntlet Of Slaying', weight: 500, bulk: 2000, buy: 3780, sell: 2100, ac: 0, sprite: { offset: ItemOffsets.GauntletOfSlaying } },
            GauntletOfSlayingS_S: { name: 'Gauntlet Of Slaying Strong', weight: 500, bulk: 2000, buy: 7560, sell: 4200, ac: 0, sprite: { offset: ItemOffsets.GauntletOfSlaying } },
            GauntletOfSlayingVS_VS: { name: 'Gauntlet Of Slaying Very Strong', weight: 500, bulk: 2000, buy: 13125, sell: 7500, ac: 0, sprite: { offset: ItemOffsets.GauntletOfSlaying } },
            GauntletOfDexterity: { name: 'Gauntlet Of Dexterity', weight: 500, bulk: 2000, buy: 3240, sell: 1800, ac: 5, sprite: { offset: ItemOffsets.GauntletEnchanted } },
            GauntletOfDexterityS: { name: 'Gauntlet Of Dexterity Strong', weight: 500, bulk: 2000, buy: 7020, sell: 3900, ac: 5, sprite: { offset: ItemOffsets.GauntletEnchanted } },
            GauntletOfDexterityVS: { name: 'Gauntlet Of Dexterity Very Strong', weight: 500, bulk: 2000, buy: 12960, sell: 7200, ac: 5, sprite: { offset: ItemOffsets.GauntletEnchanted } },
            GauntletOfStrength: { name: 'Gauntlet Of Strength', weight: 500, bulk: 2000, buy: 3240, sell: 1800, ac: 5, sprite: { offset: ItemOffsets.GauntletEnchanted } },
            GauntletOfStrengthS: { name: 'Gauntlet Of Strength Strong', weight: 500, bulk: 2000, buy: 0, sell: 0, ac: 5, sprite: { offset: ItemOffsets.GauntletEnchanted } },
            GauntletOfStrengthVS: { name: 'Gauntlet Of Strength Very Strong', weight: 500, bulk: 2000, buy: 12960, sell: 7200, ac: 5, sprite: { offset: ItemOffsets.GauntletEnchanted } }
        },
        Belt: {
            TwoSlotBelt: { name: 'Two Slot Belt', weight: 300, bulk: 300, buy: NaN, sell: NaN, level: NaN, weightCap: 2100, bulkCap: 3100, slot: 2, sprite: { offset: ItemOffsets.SlotBelt } },
            ThreeSlotBelt: { name: 'Three Slot Belt', weight: 300, bulk: 300, buy: NaN, sell: NaN, level: NaN, weightCap: 2600, bulkCap: 3600, slot: 3, sprite: { offset: ItemOffsets.SlotBelt } },
            FourSlotBelt: { name: 'Four Slot Belt', weight: 300, bulk: 300, buy: NaN, sell: NaN, level: NaN, weightCap: 3100, bulkCap: 4100, slot: 4, sprite: { offset: ItemOffsets.SlotBelt } },
            UtilityBelt: { name: 'Utility Belt', weight: 1350, bulk: 1800, buy: NaN, sell: NaN, level: NaN, weightCap: 3100, bulkCap: 4100, slot: 2, slotScroll: 4, slotPotion: 4, sprite: { offset: ItemOffsets.UtilityBelt } },
            WandQuiverBelt: { name: 'Wand Quiver Belt', weight: 300, bulk: 300, buy: NaN, sell: NaN, level: NaN, weightCap: 3100, bulkCap: 4100, slot: 2, slotWand: 4, sprite: { offset: ItemOffsets.WandQuiverBelt } }
        },
        Purse: {
            Purse: { name: 'Purse', weight: 300, bulk: 300, buy: NaN, sell: NaN, level: NaN, weightCap: 100300, bulkCap: 100300, sprite: { offset: ItemOffsets.Purse } }
        },
        Bag: {
            SmallBag: { name: 'Small Bag', weight: 300, bulk: 500, buy: NaN, sell: NaN, level: NaN, weightCap: 5000, bulkCap: 6000, sprite: { offset: ItemOffsets.Bag } },
            MediumBag: { name: 'Medium Bag', weight: 500, bulk: 700, buy: NaN, sell: NaN, level: NaN, weightCap: 10000, bulkCap: 12000, sprite: { offset: ItemOffsets.Bag } },
            LargeBag: { name: 'Large Bag', weight: 900, bulk: 900, buy: NaN, sell: NaN, level: NaN, weightCap: 15000, bulkCap: 18000, sprite: { offset: ItemOffsets.Bag } }
        },
        Pack: {
            SmallPack: { name: 'Small Pack', weight: 1000, bulk: 1000, buy: NaN, sell: NaN, level: NaN, weightCap: 12000, bulkCap: 50000, sprite: { offset: ItemOffsets.Pack } },
            MediumPack: { name: 'Medium Pack', weight: 2000, bulk: 1500, buy: NaN, sell: NaN, level: NaN, weightCap: 22000, bulkCap: 75000, sprite: { offset: ItemOffsets.Pack } },
            LargePack: { name: 'Large Pack', weight: 4000, bulk: 100000, buy: NaN, sell: NaN, level: NaN, weightCap: 35000, bulkCap: 100000, sprite: { offset: ItemOffsets.Pack } }
        },
        Chest: {
            SmallChest: { name: 'Small Chest', weight: 5000, bulk: 100000, buy: NaN, sell: NaN, level: NaN, weightCap: 100000, bulkCap: 50000, sprite: { offset: ItemOffsets.Chest } },
            MediumChest: { name: 'Medium Chest', weight: 15000, bulk: 150000, buy: NaN, sell: NaN, level: NaN, weightCap: 100000, bulkCap: 150000, sprite: { offset: ItemOffsets.Chest } },
            LargeChest: { name: 'Large Chest', weight: 25000, bulk: 250000, buy: NaN, sell: NaN, level: NaN, weightCap: 100000, bulkCap: 250000, sprite: { offset: ItemOffsets.Chest } }
        },
        PackOfHolding: {
            EnchantedSmallPackOfHolding: { name: 'Enchanted Small Pack Of Holding', weight: 5000, bulk: 75000, buy: NaN, sell: NaN, level: NaN, weightCap: 50000, bulkCap: 150000, sprite: { offset: ItemOffsets.EnchantedPack } },
            EnchantedMediumPackOfHolding: { name: 'Enchanted Medium Pack Of Holding', weight: 7500, bulk: 100000, buy: NaN, sell: NaN, level: NaN, weightCap: 75000, bulkCap: 200000, sprite: { offset: ItemOffsets.EnchantedPack } },
            EnchantedLargePackOfHolding: { name: 'Enchanted Large Pack Of Holding', weight: 10000, bulk: 125000, buy: NaN, sell: NaN, level: NaN, weightCap: 100000, bulkCap: 250000, sprite: { offset: ItemOffsets.EnchantedPack } }
        }
    }
};

var ASCIITiles = {
    '^': CoTWContent.Tiles.Rock,
    ',': CoTWContent.Tiles.Grass,
    'o': CoTWContent.Tiles.DarkDgn,
    '~': CoTWContent.Tiles.Water,
    '.': CoTWContent.Tiles.Path,
    'O': CoTWContent.Tiles.LitDgn,
    '_': CoTWContent.Tiles.PathRock,
    ';': CoTWContent.Tiles.PathGrass,
    'd': CoTWContent.Tiles.WallDarkDgn,
    'w': CoTWContent.Tiles.WaterGrass,
    'W': CoTWContent.Tiles.WaterPath,
    'D': CoTWContent.Tiles.WallLitDgn,
    'g': CoTWContent.Tiles.Grass50Cave50,
    'G': CoTWContent.Tiles.Grass10Cave90,
    'c': CoTWContent.Tiles.White50Cave50,
    'C': CoTWContent.Tiles.White90Cave10,
    '=': CoTWContent.Tiles.Crop,
    '+': CoTWContent.Tiles.Entry,
    '#': CoTWContent.Tiles.Building,
    '[': CoTWContent.Buildings.DoorClosed,
    '/': CoTWContent.Buildings.DoorOpen,
    '!': CoTWContent.Buildings.Sign
};
//# sourceMappingURL=sprites.js.map
